# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d64917496dba76613a08123a953a3365f05ff415eb289b6e373e0e716851338c6904de7d99bfad5ba0b51bde446deb098e056addb51a74eb069e2919f446b2

test:
  secret_key_base: 3babaade156b6dffe092c2f7ccd83d39c0e2f999b00176a807f0f7e8403cc059b5176009e6ab01f6bacb9c2267fc6785cd3651ace09c3018f1f3ff3d144597be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
